config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :wigs do
    resources :bookings, only: [:new, :create, :destroy, :update]
  end

  get 'dashboard_client', to: 'pages#dashboard_client', as: :dashboard_client
  get 'dashboard_owner', to: 'pages#dashboard_owner', as: :dashboard_owner
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :wig
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :wigs
  has_many :bookings_as_owner, through: :wigs, source: :bookings
end

app/models/wig.rb
class Wig < ApplicationRecord
  belongs_to :user
  has_many :bookings
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
  end

  def create
    @wig = Wig.find(params[:wig_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.wig = @wig
    if @booking.save
      redirect_to dashboard_client_path
    else
      render @wig
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = params[:status]
    @booking.save

   redirect_to dashboard_owner_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :message, :status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user! , only: [:home]

  def home
    @wigs = Wig.first(4)
  end

  def dashboard_client
    @bookings = current_user.bookings
  end


  def dashboard_owner
    @wigs = current_user.wigs
    @bookings_as_owner = current_user.bookings_as_owner
  end

  def wig_params
    params.require(:wig).permit(:title, :photo, :description, :price, :color, :size, :photo_cache)
  end
end

app/controllers/wigs_controller.rb
class WigsController < ApplicationController
  skip_before_action :authenticate_user! , only: [:index, :show]

  def index
    if params[:search].present? && params["search"]["query"] == ""
      @wigs = Wig.all
    elsif params[:search].present?
      sql_query = " \
      wigs.title @@ :search \
      OR wigs.description @@ :search \
      OR wigs.color @@ :search \
      "
      @wigs = Wig.where(sql_query, search: "%#{params["search"]["query"]}%")
    else
      @wigs = Wig.all
    end

    @markers = @wigs.map do |wig|
      {
        lat: wig.latitude,
        lng: wig.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { wig: wig }),
        image_url: helpers.asset_url('https://res.cloudinary.com/dc875ky15/image/upload/v1562854525/man-bald_1f468-200d-1f9b2_ghllek.png')
      }
    end
  end

  def new
    @wig = Wig.new
  end

  def show
    @wig = Wig.find(params[:id])
    @booking = Booking.new
  end

  def create
    @wig = Wig.new(wig_params)
    @wig.user = current_user
    if @wig.save
       redirect_to dashboard_owner_path
    else
      render 'new'
    end
  end

  def edit
    @wig = Wig.find(params[:id])
  end

  def update
    @wig = Wig.find(params[:id])
    @wig.update(wig_params)
    redirect_to wig_path(params[:id])
  end

  def destroy
    @wig = Wig.find(params[:id])
    @wig.destroy
    redirect_to dashboard_path
  end


  private

  def wig_params

    params.require(:wig).permit(:title, :photo, :description, :price, :color, :size, :photo_cache, :address
    )

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HAIRBNB</title>


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <br>
  <h2>My wigboard</h2>
  <br>
  <p>Peter Smith 👤</p>
  <p>Expert wigger ⭐️⭐️</p>
  <p>63 wigs rentals 🎯</p>
  <br>
  <h2>My wigs</h2>
  <br>
  <div class="card-request">
    <img src="https://res.cloudinary.com/dc875ky15/image/upload/v1562752188/U36167_bw2g2b.jpg">
    <div class="card-request-infos">
      <h2>Jacky Sparowsi</h2>
      <p>This is the most piraty wig of all piraty wigs. You will feel like a badass pirate if you rock this pirating wig.  Happy pirating!</p>

    </div>
  </div>
  <br>
  <%= link_to "Create a new wig", new_wig_path, class: "banner-button" %>
  <br>
  <br>
  <h2>My bookings</h2>
  <br>
  <div class="card-request">
    <img src="https://res.cloudinary.com/dc875ky15/image/upload/v1562752198/42225_jcpkpw.jpg">
    <div class="card-request-infos">
      <h2>Pamela</h2>
      <p>Find your inner Pamela with our top notch Pamela Wig! Pamela it all the way.</p>
    </div>
  </div>
</div>

app/views/pages/dashboard_client.html.erb
<div class="container">
<br>
  <h2>My bookings</h2>
<br>

<% if @current_user.bookings.empty? %>
    <p>You don't have any booking!</p>
  <% else %>
      <% @bookings.each do |booking| %>
        <%= link_to wig_path(booking.wig) do %>
      <div class="card-request">

        <img src="<%= booking.wig.photo %>">
        <div class="card-request-infos">
          <h2><%= booking.wig.title %></h2>
          <p><strong>From <%= booking.start_date%> to <%= booking.end_date%></strong></p>
          <% if booking.status == "accept"%>
          <div class="request-ribbon" style="background-color: #39CA73">
            <span>Confirmed</span>
            <% elsif booking.status == "decline" %>
            <div class="request-ribbon" style="background-color: #FF0000">
            <span>Declined</span>
            <%else %>
             <div class="request-ribbon" style="background-color:  #FF4500">
            <span>Pending</span>
            <% end %>
          </div>
          <p><%= booking.wig.description %></p>
          <p><%= booking.wig.price %>€ per day</p>
        </div>
      </div>
        <% end %>
    <% end %>

  </div>
</div>
<% end %>

<br>
<br>
  </div>
    <%= render 'shared/footer' %>

app/views/pages/dashboard_owner.html.erb
<div class="container">
<br>
<br>

<div class="dashboard-user">
    <img width="85" class="rounded-circle alone" src="https://avatars0.githubusercontent.com/u/49415784?v=4" />
    <div class="user-infos">
      <h2>Stan L.</h2>
      <p>Expert wigger ⭐️⭐️</p>
      <p>63 wigs rentals 🎯</p>
    </div>
</div>

<br>

<h3>My wigs</h3>
  <% if @current_user.wigs.empty? %>
    <p>Offer your first wig!</p>
  <% else %>
      <% @current_user.wigs.each do |wig| %>
      <%= link_to wig_path(wig) do %>
    <div class="card-request">
     <img src="<%= wig.photo %>">
       <div class="card-request-infos">
    <h2><%= wig.title %></h2>
    <p><%= wig.description %></p>
    <p><%= wig.price %>€</p>
   </div>
      </div>
<% end %>
  <% end %>
<% end %>
  <%= link_to "Offer a new wig", new_wig_path, class: "banner-button" %>
<br>
<br>
<h3>Reservations</h3>

<% if @current_user.bookings_as_owner.empty? %>
    <p>You don't have any reservations yet :/</p>
  <% else %>
      <% @bookings_as_owner.each do |booking| %>
      <%= link_to wig_path(booking.wig) do %>

    <div class="card-request">
     <img src="<%= booking.wig.photo %>">
       <div class="card-request-infos-own">
    <h2><%= booking.wig.title %></h2>
    <p><strong>From <%= booking.start_date%> to <%= booking.end_date%></strong></p>
    <p class="hey"><%= booking.message%></p>
    <p><%= booking.wig.price %>€</p>
    <% if booking.status == "accept" %>
    <h7 class="text-success">you accepted this</h7>
    <% elsif booking.status == "decline" %>
    <h7 class="text-danger">you declined this</h7>
    <% else %>
    <%= link_to "Accept", wig_booking_path(booking.wig, booking, status: "accept"), method: :patch,  class: "request-button-accept" %>
    <%= link_to "Decline", wig_booking_path(booking.wig, booking, status: "decline"), method: :patch,  class: "request-button-decline" %>
    <% end %>
   </div>

      </div>
  <% end %>
  <% end %>
      </div>

  </div>
<% end %>
  </div>
<%= render 'shared/footer' %>

app/views/pages/home.html.erb
<div class="banner">
    <%= video_tag "https://res.cloudinary.com/dc875ky15/video/upload/v1562677272/hairbnb_nlapqi.mp4", autoplay: true, loop: true, muted: true, id: "banner-video" %>
    <div class="banner-text">
      <h1>If you <strong>suck,</strong> rent a <strong>wig</strong>!</h1>
      <p>Top quality plastic, direct from China, cheap as dirt.</p>
         <%= link_to "Book a wig", wigs_path, class: "banner-button" %>
         <%= link_to "Offer a wig", new_wig_path, class: "banner-button" %>
    </div>
</div>
<br>
<br>
<div class="container">


<h2>Pretty wigs to rock</h2>
 <br>
 <div class="container">

<div class="row">
    <% @wigs.each do |wig| %>
    <div class="col-sm-3">
       <%= link_to wig_path(wig) do %>
      <div class="card-trip">
         <%= cl_image_tag("#{wig.photo}", :transformation=>[:gravity=>"face"])%>
          <div class="card-trip-infos">
            <div>
              <h2 class="wig-title"><%=wig.title.truncate(20)%></h2>
            <p><%=wig.color.truncate(30)%></p>
          </div>
         <h2 class="card-trip-pricing"><%=wig.price%>€</h2>
        </div>
      </div>
      <% end %>
    </div>
   <% end %>
  </div>
</div>
<br>
<br>
  </div>
<%= render 'shared/footer' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <strong>a wig</strong> in Wigland.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dc875ky15/image/upload/v1562745250/hairbnb_2x_z0ddgq.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

 <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My bookings", dashboard_client_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
          <%= link_to "My wigs", dashboard_owner_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/stanlvv", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Book a wig", wigs_path, class: "dropdown-item" %>
            <%= link_to "Offer a wig", new_wig_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/wigs/_infowindow.html.erb
<!-- <div class="info"><%= wig.title %></div> -->


<div class="cards-all-info">

         <%= link_to wig_path(wig) do %>
        <div class="cardinfo">
          <img class= "image" src="<%= wig.photo%>">
            <div class="cardinfos">
              <div class="words">
                <h2 class="wig-title"><%=wig.title.truncate(20)%></h2>
                <p><%=wig.price%>€</p>
            </div>
          </div>
        </div>
      </div>
     <% end %>

app/views/wigs/edit.html.erb
<div class="container-2">
  <div class="form-wrapper">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <h2>Update ya wig</h2>

      <%= simple_form_for @wig do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :color %>
        <%= f.input :price %>
        <%= f.input :size %>
        <%= f.input :address %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, 'Save', class: 'btn-flat' %>
      <% end %>
    </div>
  </div>
</div>
</div>

<%= render 'shared/footer' %>

app/views/wigs/index.html.erb
<div class="textform">
<h2 class="rock">Rock these <strong class= "bold-text"><%= @wigs.count %></strong> Wigs</h2>

</div>
<div class="search">

<%= simple_form_for :search, url: wigs_path, method: :get do |f| %>
        <div class="search-form-control form-group">
           <input class="form-control string required" type="text" name="search[query]" id="search_query" />
            <button name="button" type="submit" class="btn btn-flat">
           <i class="fas fa-search"></i> Search
          </button>
        </div>
      <% end %>
</div>


<div class="container" id="card-container">
  <div class="cards-all">
    <div class="row">
            <% @wigs.each do |wig| %>
      <div class="col-sm-6 col-xs-6 col-md-4 column" >
         <%= link_to wig_path(wig) do %>
        <div class="card-trip">
          <img src="<%= wig.photo%>">
            <div class="card-trip-infos">
              <div>
                <h2 class="wig-title"><%=wig.title.truncate(20)%></h2>
              <p><%=wig.color.truncate(20)%></p>
            </div>
           <h2 class="card-trip-pricing"><%=wig.price%>€</h2>
          </div>
        </div>
      </div>
     <% end %>
     <% end %>
    </div>
  </div>
  <div
    id="map"
    style="width: 400px;
    height: 100vh;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

<%= render 'shared/footer' %>

app/views/wigs/new.html.erb
<div class="container-2">
  <div class="form-wrapper">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <h2>Create a new wig - you bald head</h2>

      <%= simple_form_for @wig do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :color %>
        <%= f.input :price %>
        <%= f.input :size %>
        <%= f.input :address %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, class: 'btn-flat' %>
      <% end %>
    </div>
  </div>
</div>
</div>

<%= render 'shared/footer' %>

app/views/wigs/show.html.erb
<div class="container">
  <%= link_to 'Back', :back, class: "btn btn-flat-show" %>
  <div class="horizontal-flex">
    <div class="main-image"> <img src="<%= @wig.photo %>">
    </div>
    <div class="vertical-flex">
      <div class="main-description">
        <h1>Rent <%= @wig.title %></h1>
        <p class="description">Description: <%= @wig.description %></p>
        <p class="description">Color: <%= @wig.color %></p>
        <p class="description">Size: <%= @wig.size %></p>
        <p class="description">Price: <strong class="price"><%= @wig.price%>€ </strong> per day</p>
      </div>
      <% if current_user.blank? %>
      <div class="form-wrapper">
        <p class=" subtitle">When do you want this wig?</p>
        <%= simple_form_for [@wig, @booking], method: "post" do |f| %>
        <form>
          <div class="form-row">
            <div class="col">
              <%= f.input :start_date, as: :string, required: true, input_html: {class: "datepicker"}, placeholder: "click me..."%>
            </div>
            <div class="col">
              <%= f.input :end_date, as: :string, required: true, input_html: {class: "datepicker"}, placeholder: "click me..." %>
            </div>
          </div>
        </form>
        <%= f.input :message, placeholder: "Add a message", id: "message_input" %>
        <p>You need to log-in to book a wig</p>
        <% end %>
      </div>
      <% elsif current_user.id == @wig.id %>
      <div class="wig-owner">
        <p class=" subtitle">You have put this wig online.</p>
        <%= link_to "Edit", edit_wig_path, class: "btn btn-flat-show" %>
        <%= link_to "Delete", wig_path(@wig), method: :delete, class: "btn btn-flat-show" %>
      </div>
      <% else %>
      <div class="form-wrapper">
        <p class=" subtitle">When do you want this wig?</p>
        <%= simple_form_for [@wig, @booking] do |f| %>
          <div class="form-row">
            <div class="col">
              <%= f.input :start_date, as: :string, required: true, input_html: {class: "datepicker"}, placeholder: "click me..."%>
            </div>
            <div class="col">
              <%= f.input :end_date, as: :string, required: true, input_html: {class: "datepicker"}, placeholder: "click me..." %>
            </div>
          </div>
        <%= f.input :message, placeholder: "Add a message", id: "message_input" %>
        <%= f.button :submit, "Send Wiquest", class: "btn btn-flat" %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>